### ISSUE TITLE
iri-reference should not check for URI schemes

### ISSUE THREAD

**Issue by egekorkan** [luzlab/ajv-formats-draft2019#11]
The IETF specification does not specify that the URI scheme in an `iri` should be checked. After quickly checking with the JSON Schema community, this seems to be a bug. Why was this implemented explicitly and can it be simply removed?

**Comment by luzlab** [comment]
The implementation was based on the [spec](https://datatracker.ietf.org/doc/html/rfc3987#section-2.2). I double checked and it looks like the scheme is a part of the IRI. Granted, it doesn't explicity one should parse the scheme when validating a scheme, but the scheme is definitely an integral part of an IRI.

If you can find info to the contrary, this behavior can be changed.

**Comment by egekorkan** [comment]
So it does say that scheme is part of the URI but it doesn't need to be a part of the official IANA registry.

I had found this when trying URIs that start with `mqtt://` which is not officially registered but very commonly used for specifying an MQTT broker's address

**Comment by luzlab** [comment]
After I replied yesterday, I realized that's what you meant. So technically you're correct and this library is doing more than just checking for a syntactically correct scheme.

Here's the [IETF docs](https://datatracker.ietf.org/doc/html/rfc3986#section-3.1) on schemes:

> Each URI begins with a scheme name that refers to a specification for assigning identifiers within that scheme. As such, the URI syntax is a federated and extensible naming system wherein each scheme's specification may further restrict the syntax and semantics of identifiers using that scheme.
>
> Scheme names consist of a sequence of characters beginning with a letter and followed by any combination of letters, digits, plus ("+"), period ("."), or hyphen ("-"). Although schemes are case- insensitive, the canonical form is lowercase and documents that specify schemes must do so with lowercase letters. An implementation should accept uppercase letters as equivalent to lowercase in scheme names (e.g., allow "HTTP" as well as "http") for the sake of robustness but should only produce lowercase scheme names for consistency.
>
>       `scheme      = ALPHA *( ALPHA / DIGIT / "+" / "-" / "." )`
>
> Individual schemes are not specified by this document. The process for registration of new URI schemes is defined separately by `BCP35`. The scheme registry maintains the mapping between scheme names and their specifications. Advice for designers of new URI schemes can be found in `RFC2718`. URI scheme specifications must define their own syntax so that all strings matching their scheme-specific syntax will also match the `absolute-URI` grammar, as described in Section 4.3.
>
> When presented with a URI that violates one or more scheme-specific restrictions, the scheme-specific resolution process should flag the reference as an error rather than ignore the unused parts; doing so reduces the number of equivalent URIs and helps detect abuses of the generic syntax, which might indicate that the URI has been constructed to mislead the user (Section 7.6).

The docs explicitly mention the registration process for schemes, and that the "scheme registry" can hold scheme-specific specs that further restrict the syntax of the subsequent identifiers. 

I'd argue the real problem here is that no one has bothered registering a widely used scheme that been in use for more than 20 years. That's a terrible reason to loosen up validation logic - I want to catch typos like `httsp:`, and I assume you'd like to catch `mtqq:` as well. If we validate syntax-only, we wouldn't catch either of those issues.

That said, I'm not suggesting to register `mqtt` with IANA, but please submit a PR to the [schemes](https://github.com/Munter/schemes) repo adding `mqtt` to the [list of "unofficial" schemes](https://github.com/Munter/schemes/blob/master/lib/unofficial.json). The last time this [issue](https://github.com/luzlab/ajv-formats-draft2019/issues/4) came up, it was handled fairly painlessly.

**Comment by egekorkan** [comment]
I follow your points and agree with it as well to have something usable. Doing a PR there now :)

**Comment by luzlab** [comment]
Just released v1.6.1 that updates `schemes` and adds a couple of unit tests for the new schemes.
